/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 arts.gltf --transform 
Files: arts.gltf [72.38MB] > C:\Users\mohan\Downloads\art_gallery\arts-transformed.glb [9.9MB] (86%)
Author: shinymagic (https://sketchfab.com/shinymagic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/richards-art-gallery-audio-tour-0e3e19faa6474fd5974e6a7ed1b221d8
Title: Richard's Art Gallery - Audio Tour
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF("/arts-transformed.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="RootNode" scale={0.001}>
          <group
            name="leaves"
            position={[9127.908, 2291.518, 3984.852]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <mesh
              name="leaves_trees_0"
              geometry={nodes.leaves_trees_0.geometry}
              material={materials.trees}
            />
          </group>
          <group
            name="render_butterfly"
            position={[3205.641, 1374.502, -832.375]}
            rotation={[-1.095, -0.137, -2.694]}
            scale={1.822}
          >
            <group
              name="Butterfly_Master"
              position={[-1900.76, 3860.86, 1059.653]}
              rotation={[0.073, -0.241, 2.544]}
              scale={0.076}
            >
              <group
                name="Wing_Upper_Left"
                position={[-24.445, 11.902, 0.109]}
                rotation={[0.006, 0.603, -0.003]}
              >
                <group name="Object_94" position={[302.735, -4.531, -64.708]}>
                  <mesh
                    name="Wing_Upper_Left_butterfly-baked_0"
                    geometry={
                      nodes["Wing_Upper_Left_butterfly-baked_0"].geometry
                    }
                    material={materials["butterfly-baked"]}
                  />
                </group>
                <group
                  name="Wing_Lower_Left"
                  position={[-68.566, -242.537, 4.738]}
                  rotation={[-0.002, -0.004, -1.026]}
                >
                  <group
                    name="Object_97"
                    position={[324.213, 171.833, -64.267]}
                  >
                    <mesh
                      name="Wing_Lower_Left_butterfly-baked_0"
                      geometry={
                        nodes["Wing_Lower_Left_butterfly-baked_0"].geometry
                      }
                      material={materials["butterfly-baked"]}
                    />
                  </group>
                </group>
              </group>
              <group
                name="wing_controller004"
                position={[0, -7.67, 0.004]}
                rotation={[-Math.PI / 2, 0, -0.603]}
              >
                <mesh
                  name="wing_controller004_XXX_DO_NOT_RENDER_0"
                  geometry={
                    nodes.wing_controller004_XXX_DO_NOT_RENDER_0.geometry
                  }
                  material={materials.XXX_DO_NOT_RENDER}
                />
              </group>
              <group
                name="Wing_upper_right004"
                position={[24.438, 11.902, 0.246]}
                rotation={[0.006, -0.603, 0.003]}
              >
                <group name="Object_102" position={[256.953, -4.532, -64.844]}>
                  <mesh
                    name="Wing_upper_right004_butterfly-baked_0"
                    geometry={
                      nodes["Wing_upper_right004_butterfly-baked_0"].geometry
                    }
                    material={materials["butterfly-baked"]}
                  />
                </group>
                <group
                  name="Wing_lower_right004"
                  position={[-10.094, -247.365, 66.451]}
                  rotation={[-0.003, -0.005, -1.026]}
                >
                  <group
                    name="Object_105"
                    position={[282.804, 108.721, -130.624]}
                  >
                    <mesh
                      name="Wing_lower_right004_butterfly-baked_0"
                      geometry={
                        nodes["Wing_lower_right004_butterfly-baked_0"].geometry
                      }
                      material={materials["butterfly-baked"]}
                    />
                  </group>
                </group>
              </group>
              <group
                name="Capsule419"
                position={[0, 227.479, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Capsule419_XXX_DO_NOT_RENDER_0"
                  geometry={nodes.Capsule419_XXX_DO_NOT_RENDER_0.geometry}
                  material={materials.XXX_DO_NOT_RENDER}
                />
              </group>
              <group
                name="Plane011"
                position={[-115.031, 38.418, 65.516]}
                scale={4.906}
              >
                <group name="Object_110" position={[36.852, -39.163, 0]}>
                  <mesh
                    name="Plane011_lens_flare_0"
                    geometry={nodes.Plane011_lens_flare_0.geometry}
                    material={materials.lens_flare}
                  />
                </group>
              </group>
              <mesh
                name="Butterfly_Master_XXX_DO_NOT_RENDER_0"
                geometry={nodes.Butterfly_Master_XXX_DO_NOT_RENDER_0.geometry}
                material={materials.XXX_DO_NOT_RENDER}
              />
            </group>
          </group>
          <group
            name="volume_ligiht006"
            position={[9034.638, 1895.868, -1058.869]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_113" position={[1600.96, -51.972, -411.723]}>
              <mesh
                name="volume_ligiht006_Material_#49_0"
                geometry={nodes["volume_ligiht006_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object012"
            position={[11076.502, 1798.95, -639.394]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_119" position={[-440.904, 367.504, -314.805]}>
              <mesh
                name="Object012_Material_#49_0"
                geometry={nodes["Object012_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object013"
            position={[11076.602, 2442.329, -656.034]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_122" position={[-441.004, 350.863, -958.184]}>
              <mesh
                name="Object013_Material_#49_0"
                geometry={nodes["Object013_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object014"
            position={[11076.659, 2659.707, -666.153]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_125" position={[-441.062, 340.745, -1175.563]}>
              <mesh
                name="Object014_Material_#49_0"
                geometry={nodes["Object014_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object015"
            position={[10868.623, 2198.441, -1474.46]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_128" position={[-233.025, -467.562, -714.296]}>
              <mesh
                name="Object015_Material_#49_0"
                geometry={nodes["Object015_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object016"
            position={[10103.771, 2622.589, -1001.134]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_131" position={[531.827, 5.764, -1138.445]}>
              <mesh
                name="Object016_Material_#49_0"
                geometry={nodes["Object016_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object017"
            position={[9429.378, 2198.441, -1534.467]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_134" position={[1206.22, -527.569, -714.296]}>
              <mesh
                name="Object017_Material_#49_0"
                geometry={nodes["Object017_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object018"
            position={[11076.531, 1985.713, -762.743]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_137" position={[-440.934, 359.535, -493.586]}>
              <mesh
                name="Object018_Material_#49_0"
                geometry={nodes["Object018_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object019"
            position={[10868.32, 2115.362, -1434.501]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_140" position={[-232.723, -427.603, -631.217]}>
              <mesh
                name="Object019_Material_#49_0"
                geometry={nodes["Object019_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object020"
            position={[10863.453, 1781.733, -845.326]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_143" position={[-227.855, 161.572, -297.589]}>
              <mesh
                name="Object020_Material_#49_0"
                geometry={nodes["Object020_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object021"
            position={[10864.726, 1862.876, -1005.198]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_146" position={[-229.128, 1.7, -378.731]}>
              <mesh
                name="Object021_Material_#49_0"
                geometry={nodes["Object021_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object022"
            position={[10752.125, 1774.921, -838.738]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_149" position={[-116.527, 168.16, -290.776]}>
              <mesh
                name="Object022_Material_#49_0"
                geometry={nodes["Object022_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object023"
            position={[10753.488, 1857.117, -1010.156]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_152" position={[-117.891, -3.258, -372.972]}>
              <mesh
                name="Object023_Material_#49_0"
                geometry={nodes["Object023_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object024"
            position={[10757.895, 2198.441, -1537.054]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_155" position={[-122.297, -530.156, -714.297]}>
              <mesh
                name="Object024_Material_#49_0"
                geometry={nodes["Object024_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object025"
            position={[10757.476, 2113.723, -1484.984]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_158" position={[-121.878, -478.087, -629.579]}>
              <mesh
                name="Object025_Material_#49_0"
                geometry={nodes["Object025_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object026"
            position={[9895.226, 2198.441, -1584.821]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_161" position={[740.372, -577.923, -714.296]}>
              <mesh
                name="Object026_Material_#49_0"
                geometry={nodes["Object026_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object027"
            position={[9039.724, 2198.441, -1331.812]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_164" position={[1595.874, -324.914, -714.296]}>
              <mesh
                name="Object027_Material_#49_0"
                geometry={nodes["Object027_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object028"
            position={[10455.191, 2111.359, -1558.021]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_167" position={[180.406, -551.123, -627.215]}>
              <mesh
                name="Object028_Material_#49_0"
                geometry={nodes["Object028_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object029"
            position={[9038.739, 2124.746, -1331.815]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_170" position={[1596.858, -324.917, -640.602]}>
              <mesh
                name="Object029_Material_#49_0"
                geometry={nodes["Object029_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object030"
            position={[10449.019, 1765.089, -834.094]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_173" position={[186.579, 172.804, -280.945]}>
              <mesh
                name="Object030_Material_#49_0"
                geometry={nodes["Object030_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object031"
            position={[10450.571, 1848.805, -1024.05]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_176" position={[185.026, -17.152, -364.66]}>
              <mesh
                name="Object031_Material_#49_0"
                geometry={nodes["Object031_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object032"
            position={[10101.122, 1768.35, -776.283]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_179" position={[534.476, 230.615, -284.206]}>
              <mesh
                name="Object032_Material_#49_0"
                geometry={nodes["Object032_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object033"
            position={[10101.651, 1894.757, -827.553]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_182" position={[533.946, 179.345, -410.613]}>
              <mesh
                name="Object033_Material_#49_0"
                geometry={nodes["Object033_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object034"
            position={[10103.005, 2390.56, -938.16]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_185" position={[532.593, 68.738, -906.415]}>
              <mesh
                name="Object034_Material_#49_0"
                geometry={nodes["Object034_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object035"
            position={[10455.979, 2198.441, -1642.591]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_188" position={[179.618, -635.693, -714.297]}>
              <mesh
                name="Object035_Material_#49_0"
                geometry={nodes["Object035_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object036"
            position={[9887.63, 1780.894, -866.822]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_191" position={[747.968, 140.076, -296.75]}>
              <mesh
                name="Object036_Material_#49_0"
                geometry={nodes["Object036_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object037"
            position={[9894.268, 2115.16, -1529.385]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_194" position={[741.33, -522.488, -631.015]}>
              <mesh
                name="Object037_Material_#49_0"
                geometry={nodes["Object037_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object038"
            position={[9421.896, 1789.237, -880.472]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_197" position={[1213.702, 126.426, -305.093]}>
              <mesh
                name="Object038_Material_#49_0"
                geometry={nodes["Object038_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object039"
            position={[9889.344, 1862.166, -1042.017]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_200" position={[746.254, -35.119, -378.022]}>
              <mesh
                name="Object039_Material_#49_0"
                geometry={nodes["Object039_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object040"
            position={[9423.612, 1869.219, -1045.141]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_203" position={[1211.985, -38.243, -385.075]}>
              <mesh
                name="Object040_Material_#49_0"
                geometry={nodes["Object040_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object041"
            position={[9428.399, 2117.167, -1490.281]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_206" position={[1207.198, -483.383, -633.022]}>
              <mesh
                name="Object041_Material_#49_0"
                geometry={nodes["Object041_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object042"
            position={[9032.965, 1820.759, -936.314]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_209" position={[1602.633, 70.583, -336.615]}>
              <mesh
                name="Object042_Material_#49_0"
                geometry={nodes["Object042_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object044"
            position={[9408.896, 920.359, 2270.137]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_212" position={[1226.702, 3277.035, 563.785]}>
              <mesh
                name="Object044_Material_#49_0"
                geometry={nodes["Object044_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object045"
            position={[8785.727, 920.359, 1937.978]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_215" position={[1849.871, 2944.876, 563.785]}>
              <mesh
                name="Object045_Material_#49_0"
                geometry={nodes["Object045_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object047"
            position={[9405.336, 603.865, 2416.192]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_220" position={[1230.262, 3423.09, 880.279]}>
              <mesh
                name="Object047_Material_#49_0"
                geometry={nodes["Object047_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object048"
            position={[8778.921, 603.865, 2373.489]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_223" position={[1856.677, 3380.387, 880.279]}>
              <mesh
                name="Object048_Material_#49_0"
                geometry={nodes["Object048_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object049"
            position={[8787.396, 998.014, 1828.879]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_226" position={[1848.201, 2835.777, 486.131]}>
              <mesh
                name="Object049_Material_#49_0"
                geometry={nodes["Object049_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object050"
            position={[9084.258, 920.359, 1937.978]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_229" position={[1551.34, 2944.876, 563.785]}>
              <mesh
                name="Object050_Material_#49_0"
                geometry={nodes["Object050_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object051"
            position={[9129.477, 603.865, 2373.489]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_232" position={[1506.121, 3380.387, 880.279]}>
              <mesh
                name="Object051_Material_#49_0"
                geometry={nodes["Object051_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object052"
            position={[9408.064, 681.52, 2302.017]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_235" position={[1227.533, 3308.915, 802.625]}>
              <mesh
                name="Object052_Material_#49_0"
                geometry={nodes["Object052_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object053"
            position={[9408.896, 1118.507, 2267.894]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_238" position={[1226.702, 3274.792, 365.637]}>
              <mesh
                name="Object053_Material_#49_0"
                geometry={nodes["Object053_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object054"
            position={[8780.591, 681.52, 2264.389]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_241" position={[1855.007, 3271.287, 802.625]}>
              <mesh
                name="Object054_Material_#49_0"
                geometry={nodes["Object054_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object056"
            position={[9111.195, 681.52, 2264.389]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_246" position={[1524.402, 3271.287, 802.625]}>
              <mesh
                name="Object056_Material_#49_0"
                geometry={nodes["Object056_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object057"
            position={[9086.559, 920.359, 1937.978]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_249" position={[1549.039, 2944.876, 563.785]}>
              <mesh
                name="Object057_Material_#49_0"
                geometry={nodes["Object057_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="leaves001"
            position={[-5620.938, 2291.518, 3602.46]}
            rotation={[-Math.PI / 2, 0, 0.059]}
          >
            <mesh
              name="leaves001_trees_0"
              geometry={nodes.leaves001_trees_0.geometry}
              material={materials.trees}
            />
          </group>
          <group
            name="Object060"
            position={[-6293.371, 1798.95, -639.394]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_258" position={[-440.904, 367.504, -314.805]}>
              <mesh
                name="Object060_Material_#49_0"
                geometry={nodes["Object060_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object061"
            position={[-6293.271, 2442.329, -656.034]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_261" position={[-441.004, 350.863, -958.184]}>
              <mesh
                name="Object061_Material_#49_0"
                geometry={nodes["Object061_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object062"
            position={[-6293.213, 2659.707, -666.153]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_264" position={[-441.062, 340.745, -1175.563]}>
              <mesh
                name="Object062_Material_#49_0"
                geometry={nodes["Object062_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object063"
            position={[-6501.25, 2198.441, -1474.46]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_267" position={[-233.025, -467.562, -714.296]}>
              <mesh
                name="Object063_Material_#49_0"
                geometry={nodes["Object063_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object064"
            position={[-7266.102, 2622.589, -1001.134]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_270" position={[531.827, 5.764, -1138.445]}>
              <mesh
                name="Object064_Material_#49_0"
                geometry={nodes["Object064_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object065"
            position={[-7940.495, 2198.441, -1534.467]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_273" position={[1206.22, -527.569, -714.296]}>
              <mesh
                name="Object065_Material_#49_0"
                geometry={nodes["Object065_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object066"
            position={[-6293.341, 1985.713, -762.743]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_276" position={[-440.934, 359.535, -493.586]}>
              <mesh
                name="Object066_Material_#49_0"
                geometry={nodes["Object066_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object067"
            position={[-6501.552, 2115.362, -1434.501]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_279" position={[-232.723, -427.603, -631.217]}>
              <mesh
                name="Object067_Material_#49_0"
                geometry={nodes["Object067_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object068"
            position={[-6506.419, 1781.733, -845.326]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_282" position={[-227.855, 161.572, -297.589]}>
              <mesh
                name="Object068_Material_#49_0"
                geometry={nodes["Object068_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object069"
            position={[-6505.147, 1862.876, -1005.198]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_285" position={[-229.128, 1.7, -378.731]}>
              <mesh
                name="Object069_Material_#49_0"
                geometry={nodes["Object069_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object070"
            position={[-6617.748, 1774.921, -838.738]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_288" position={[-116.527, 168.16, -290.776]}>
              <mesh
                name="Object070_Material_#49_0"
                geometry={nodes["Object070_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object071"
            position={[-6616.384, 1857.117, -1010.156]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_291" position={[-117.891, -3.258, -372.972]}>
              <mesh
                name="Object071_Material_#49_0"
                geometry={nodes["Object071_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object072"
            position={[-6611.978, 2198.441, -1537.054]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_294" position={[-122.297, -530.156, -714.297]}>
              <mesh
                name="Object072_Material_#49_0"
                geometry={nodes["Object072_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object073"
            position={[-6612.397, 2113.723, -1484.984]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_297" position={[-121.878, -478.087, -629.579]}>
              <mesh
                name="Object073_Material_#49_0"
                geometry={nodes["Object073_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object074"
            position={[-7474.647, 2198.441, -1584.821]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_300" position={[740.372, -577.923, -714.296]}>
              <mesh
                name="Object074_Material_#49_0"
                geometry={nodes["Object074_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object075"
            position={[-8330.149, 2198.441, -1331.812]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_303" position={[1595.874, -324.914, -714.296]}>
              <mesh
                name="Object075_Material_#49_0"
                geometry={nodes["Object075_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object076"
            position={[-6914.681, 2111.359, -1558.021]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_306" position={[180.406, -551.123, -627.215]}>
              <mesh
                name="Object076_Material_#49_0"
                geometry={nodes["Object076_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object077"
            position={[-8331.134, 2124.746, -1331.815]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_309" position={[1596.858, -324.917, -640.602]}>
              <mesh
                name="Object077_Material_#49_0"
                geometry={nodes["Object077_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object078"
            position={[-6920.854, 1765.089, -834.094]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_312" position={[186.579, 172.804, -280.945]}>
              <mesh
                name="Object078_Material_#49_0"
                geometry={nodes["Object078_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object079"
            position={[-6919.301, 1848.805, -1024.05]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_315" position={[185.026, -17.152, -364.66]}>
              <mesh
                name="Object079_Material_#49_0"
                geometry={nodes["Object079_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object080"
            position={[-7268.75, 1768.35, -776.283]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_318" position={[534.476, 230.615, -284.206]}>
              <mesh
                name="Object080_Material_#49_0"
                geometry={nodes["Object080_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object081"
            position={[-7268.221, 1894.757, -827.553]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_321" position={[533.946, 179.345, -410.613]}>
              <mesh
                name="Object081_Material_#49_0"
                geometry={nodes["Object081_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object082"
            position={[-7266.868, 2390.56, -938.16]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_324" position={[532.593, 68.738, -906.415]}>
              <mesh
                name="Object082_Material_#49_0"
                geometry={nodes["Object082_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object083"
            position={[-6913.893, 2198.441, -1642.591]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_327" position={[179.618, -635.693, -714.297]}>
              <mesh
                name="Object083_Material_#49_0"
                geometry={nodes["Object083_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object084"
            position={[-7482.243, 1780.894, -866.822]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_330" position={[747.968, 140.076, -296.75]}>
              <mesh
                name="Object084_Material_#49_0"
                geometry={nodes["Object084_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object085"
            position={[-7475.605, 2115.16, -1529.385]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_333" position={[741.33, -522.488, -631.015]}>
              <mesh
                name="Object085_Material_#49_0"
                geometry={nodes["Object085_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object086"
            position={[-7947.977, 1789.237, -880.472]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_336" position={[1213.702, 126.426, -305.093]}>
              <mesh
                name="Object086_Material_#49_0"
                geometry={nodes["Object086_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object087"
            position={[-7480.529, 1862.166, -1042.017]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_339" position={[746.254, -35.119, -378.022]}>
              <mesh
                name="Object087_Material_#49_0"
                geometry={nodes["Object087_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object088"
            position={[-7946.26, 1869.219, -1045.141]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_342" position={[1211.985, -38.243, -385.075]}>
              <mesh
                name="Object088_Material_#49_0"
                geometry={nodes["Object088_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object089"
            position={[-7941.473, 2117.167, -1490.281]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_345" position={[1207.198, -483.383, -633.022]}>
              <mesh
                name="Object089_Material_#49_0"
                geometry={nodes["Object089_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object090"
            position={[-8336.908, 1820.759, -936.314]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_348" position={[1602.633, 70.583, -336.615]}>
              <mesh
                name="Object090_Material_#49_0"
                geometry={nodes["Object090_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="volume_ligiht007"
            position={[-8335.235, 1895.868, -1058.869]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="Object_351" position={[1600.96, -51.972, -411.723]}>
              <mesh
                name="volume_ligiht007_Material_#49_0"
                geometry={nodes["volume_ligiht007_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object091"
            position={[-6515.634, 920.359, 2270.137]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_355" position={[1226.702, 3277.035, 563.785]}>
              <mesh
                name="Object091_Material_#49_0"
                geometry={nodes["Object091_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object092"
            position={[-5892.465, 920.359, 1937.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_358" position={[1849.871, 2944.876, 563.785]}>
              <mesh
                name="Object092_Material_#49_0"
                geometry={nodes["Object092_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object094"
            position={[-6512.074, 603.865, 2416.192]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_363" position={[1230.262, 3423.09, 880.279]}>
              <mesh
                name="Object094_Material_#49_0"
                geometry={nodes["Object094_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object095"
            position={[-5885.659, 603.865, 2373.489]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_366" position={[1856.677, 3380.387, 880.279]}>
              <mesh
                name="Object095_Material_#49_0"
                geometry={nodes["Object095_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object096"
            position={[-5894.135, 998.014, 1828.879]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_369" position={[1848.201, 2835.777, 486.131]}>
              <mesh
                name="Object096_Material_#49_0"
                geometry={nodes["Object096_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object097"
            position={[-6190.996, 920.359, 1937.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_372" position={[1551.34, 2944.876, 563.785]}>
              <mesh
                name="Object097_Material_#49_0"
                geometry={nodes["Object097_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object098"
            position={[-6236.215, 603.865, 2373.489]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_375" position={[1506.121, 3380.387, 880.279]}>
              <mesh
                name="Object098_Material_#49_0"
                geometry={nodes["Object098_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object099"
            position={[-6514.803, 681.52, 2302.017]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_378" position={[1227.533, 3308.915, 802.625]}>
              <mesh
                name="Object099_Material_#49_0"
                geometry={nodes["Object099_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object100"
            position={[-6515.634, 1118.507, 2267.894]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_381" position={[1226.702, 3274.792, 365.637]}>
              <mesh
                name="Object100_Material_#49_0"
                geometry={nodes["Object100_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object101"
            position={[-5887.329, 681.52, 2264.389]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_384" position={[1855.007, 3271.287, 802.625]}>
              <mesh
                name="Object101_Material_#49_0"
                geometry={nodes["Object101_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object103"
            position={[-6217.934, 681.52, 2264.389]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_389" position={[1524.402, 3271.287, 802.625]}>
              <mesh
                name="Object103_Material_#49_0"
                geometry={nodes["Object103_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="Object104"
            position={[-6193.297, 920.359, 1937.978]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={-1}
          >
            <group name="Object_392" position={[1549.039, 2944.876, 563.785]}>
              <mesh
                name="Object104_Material_#49_0"
                geometry={nodes["Object104_Material_#49_0"].geometry}
                material={materials.Material_49}
              />
            </group>
          </group>
          <group
            name="dream_catcher"
            position={[1577.894, 3297.746, -132.145]}
            rotation={[0, Math.PI / 6, 0]}
          >
            <group
              name="dream_catcher_left"
              position={[-113.109, -414.158, -2.321]}
              rotation={[0, 0.175, 0]}
            >
              <group name="Object_402" position={[111.91, -151.215, -0.223]}>
                <mesh
                  name="dream_catcher_left_dream_catcher_0"
                  geometry={nodes.dream_catcher_left_dream_catcher_0.geometry}
                  material={materials.dream_catcher}
                />
              </group>
              <group
                name="Plane002"
                position={[-8.792, -153.379, 1.288]}
                rotation={[-0.529, Math.PI / 2, 0]}
              >
                <group name="Object_405" position={[172.808, 0.648, 0]}>
                  <mesh
                    name="Plane002_light_beam_0"
                    geometry={nodes.Plane002_light_beam_0.geometry}
                    material={materials.light_beam}
                  />
                </group>
              </group>
              <group
                name="Plane009"
                position={[-8.792, -153.379, 1.288]}
                rotation={[-0.529, 1.222, 0]}
                scale={0.406}
              >
                <group name="Object_408" position={[172.808, 0.648, 0]}>
                  <mesh
                    name="Plane009_light_beam_0"
                    geometry={nodes.Plane009_light_beam_0.geometry}
                    material={materials.light_beam}
                  />
                </group>
              </group>
              <group
                name="Plane010"
                position={[-8.792, -153.379, 1.288]}
                rotation={[-2.295, 1.237, 2.406]}
                scale={0.406}
              >
                <group name="Object_411" position={[172.808, 0.648, 0]}>
                  <mesh
                    name="Plane010_light_beam_0"
                    geometry={nodes.Plane010_light_beam_0.geometry}
                    material={materials.light_beam}
                  />
                </group>
              </group>
            </group>
            <group
              name="dream_catcher_right"
              position={[79.757, -406.365, 0]}
              rotation={[0, -0.175, 0]}
            >
              <group name="Object_414" position={[-79.918, -159.007, 0.347]}>
                <mesh
                  name="dream_catcher_right_dream_catcher_0"
                  geometry={nodes.dream_catcher_right_dream_catcher_0.geometry}
                  material={materials.dream_catcher}
                />
              </group>
              <group
                name="Plane003"
                position={[-1.094, -107.735, -4.029]}
                rotation={[-0.529, Math.PI / 2, 0]}
                scale={2.625}
              >
                <group name="Object_417" position={[172.808, 0.648, 0]}>
                  <mesh
                    name="Plane003_light_beam_0"
                    geometry={nodes.Plane003_light_beam_0.geometry}
                    material={materials.light_beam}
                  />
                </group>
              </group>
              <group
                name="Plane007"
                position={[-1.094, -101.128, -2.954]}
                rotation={[-0.878, Math.PI / 3, 0]}
                scale={0.482}
              >
                <group name="Object_420" position={[172.808, 0.648, 0]}>
                  <mesh
                    name="Plane007_light_beam_0"
                    geometry={nodes.Plane007_light_beam_0.geometry}
                    material={materials.light_beam}
                  />
                </group>
              </group>
              <group
                name="Plane008"
                position={[-1.018, -101.431, -2.916]}
                rotation={[-2.692, 1.14, 2.525]}
                scale={0.482}
              >
                <group name="Object_423" position={[172.808, 0.648, 0]}>
                  <mesh
                    name="Plane008_light_beam_0"
                    geometry={nodes.Plane008_light_beam_0.geometry}
                    material={materials.light_beam}
                  />
                </group>
              </group>
            </group>
            <group name="Object_399" position={[0, -565.373, 0]}>
              <mesh
                name="dream_catcher_dream_catcher_0"
                geometry={nodes.dream_catcher_dream_catcher_0.geometry}
                material={materials.dream_catcher}
              />
            </group>
            <group
              name="Plane001"
              position={[-15.881, -402.407, 1.805]}
              rotation={[-0.529, Math.PI / 2, 0]}
              scale={2.336}
            >
              <group name="Object_426" position={[172.808, 0.648, 0]}>
                <mesh
                  name="Plane001_light_beam_0"
                  geometry={nodes.Plane001_light_beam_0.geometry}
                  material={materials.light_beam}
                />
              </group>
            </group>
            <group
              name="Plane004"
              position={[-15.881, -395.395, 1.77]}
              rotation={[-2.798, 1.222, Math.PI]}
              scale={2.336}
            >
              <group name="Object_429" position={[172.808, 0.648, 0]}>
                <mesh
                  name="Plane004_light_beam_0"
                  geometry={nodes.Plane004_light_beam_0.geometry}
                  material={materials.light_beam}
                />
              </group>
            </group>
            <group
              name="Plane005"
              position={[-15.881, -395.395, 1.77]}
              rotation={[-0.802, 1.019, -0.089]}
              scale={2.336}
            >
              <group name="Object_432" position={[172.808, 0.648, 0]}>
                <mesh
                  name="Plane005_light_beam_0"
                  geometry={nodes.Plane005_light_beam_0.geometry}
                  material={materials.light_beam}
                />
              </group>
            </group>
            <group
              name="Plane006"
              position={[-21.035, -396.164, 0.819]}
              rotation={[-0.857, 0.41, -0.051]}
              scale={2.336}
            >
              <group name="Object_435" position={[172.808, 0.648, 0]}>
                <mesh
                  name="Plane006_light_beam_0"
                  geometry={nodes.Plane006_light_beam_0.geometry}
                  material={materials.light_beam}
                />
              </group>
            </group>
          </group>
          <group name="red" position={[1569.76, 2386.741, -807.164]}>
            <mesh
              name="red_projection_1_0"
              geometry={nodes.red_projection_1_0.geometry}
              material={materials.projection_1}
            />
          </group>
          <group name="top" position={[1230.485, 2386.741, -808.693]}>
            <mesh
              name="top_projection_2_0"
              geometry={nodes.top_projection_2_0.geometry}
              material={materials.projection_2}
            />
          </group>
          <group name="Object109" position={[438.601, 2386.741, -807.164]}>
            <mesh
              name="Object109_projection_1_0"
              geometry={nodes.Object109_projection_1_0.geometry}
              material={materials.projection_1}
            />
          </group>
        </group>
        <mesh
          name="round_table_round_table_0"
          geometry={nodes.round_table_round_table_0.geometry}
          material={materials.round_table}
          position={[-8.697, 0.462, -0.034]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="curtain_rail002_curtain_rail_0"
          geometry={nodes.curtain_rail002_curtain_rail_0.geometry}
          material={materials.curtain_rail}
          position={[-7.01, 2.428, 3.371]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Loveknot_and_tess_Loveknot_Manual_Bake_0"
          geometry={nodes.Loveknot_and_tess_Loveknot_Manual_Bake_0.geometry}
          material={materials.Loveknot_Manual_Bake}
          position={[5.384, 1.557, 0.775]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="boat_boat_manual_bake_0"
          geometry={nodes.boat_boat_manual_bake_0.geometry}
          material={materials.boat_manual_bake}
          position={[-2.138, 1.557, -0.967]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="end_frame_end_frame_manual_bake_0"
          geometry={nodes.end_frame_end_frame_manual_bake_0.geometry}
          material={materials.end_frame_manual_bake}
          position={[-12.552, 1.535, 0.201]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="horse_and_squirrel_seal_manual_bake_0"
          geometry={nodes.horse_and_squirrel_seal_manual_bake_0.geometry}
          material={materials.seal_manual_bake}
          position={[-5.535, 1.645, -0.098]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="fern_proxy_plant_0"
          geometry={nodes.fern_proxy_plant_0.geometry}
          material={materials.plant}
          position={[1.677, 0.839, -0.235]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Box019_Material_#4040_0"
          geometry={nodes["Box019_Material_#4040_0"].geometry}
          material={materials.Material_4040}
          position={[-8.688, 3.263, -0.04]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="spotlights_Material_#3394_0"
          geometry={nodes["spotlights_Material_#3394_0"].geometry}
          material={materials.Material_3394}
          position={[0.052, 2.53, 0.67]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Eddie_and_horse_propinquity_early_manual_bake_0"
          geometry={
            nodes.Eddie_and_horse_propinquity_early_manual_bake_0.geometry
          }
          material={materials.propinquity_early_manual_bake}
          position={[12.8, 1.645, 3.821]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="jake_and_london_eye_london_eye_manual_bake_0"
          geometry={nodes.jake_and_london_eye_london_eye_manual_bake_0.geometry}
          material={materials.london_eye_manual_bake}
          position={[8.813, 1.09, 1.611]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="SIMON_AND_JAKE_simon_manual_bake_0"
          geometry={nodes.SIMON_AND_JAKE_simon_manual_bake_0.geometry}
          material={materials.simon_manual_bake}
          position={[7.951, 1.306, -0.969]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="weeebo_and_tiggy_weebo_manual_bake_0"
          geometry={nodes.weeebo_and_tiggy_weebo_manual_bake_0.geometry}
          material={materials.weebo_manual_bake}
          position={[1.257, 1.654, -0.978]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="seal_2_jag_manual_bake_0"
          geometry={nodes.seal_2_jag_manual_bake_0.geometry}
          material={materials.jag_manual_bake}
          position={[-10.303, 1.437, 3.512]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="coving01_skirting_0"
          geometry={nodes.coving01_skirting_0.geometry}
          material={materials.skirting}
          position={[-8.713, 0.129, -0.132]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Building_C_Walls_0"
          geometry={nodes.Building_C_Walls_0.geometry}
          material={materials.Walls}
          position={[-8.636, -0.009, -0.087]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Building_B_Material_#3993_0"
          geometry={nodes["Building_B_Material_#3993_0"].geometry}
          material={materials.Material_3993}
          position={[-8.745, 0, 13.541]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="curtain001_Material_#4028_0"
          geometry={nodes["curtain001_Material_#4028_0"].geometry}
          material={materials.Material_4028}
          position={[2.18, 1.228, 3.372]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="skirting_skirting_0"
          geometry={nodes.skirting_skirting_0.geometry}
          material={materials.skirting_0}
          position={[-8.713, 2.501, -0.145]}
          rotation={[Math.PI / 2, 0, -3.141]}
          scale={[-0.001, 0.001, 0.001]}
        />
        <mesh
          name="water_fountain_Material_#4195_0"
          geometry={nodes["water_fountain_Material_#4195_0"].geometry}
          material={materials.Material_4195}
          position={[-8.662, 0.978, -0.034]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="holly_plant_and_book_Material_#3550_0"
          geometry={nodes["holly_plant_and_book_Material_#3550_0"].geometry}
          material={materials.Material_3550}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="corridor_volume_corridor_volume_0"
          geometry={nodes.corridor_volume_corridor_volume_0.geometry}
          material={materials.corridor_volume}
          position={[6.846, 3.233, -0.667]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Building_A_Walls_a_0"
          geometry={nodes.Building_A_Walls_a_0.geometry}
          material={materials.Walls_a}
          position={[12.21, -0.009, -0.081]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="jakeframe_jake_manua_bake_0"
          geometry={nodes.jakeframe_jake_manua_bake_0.geometry}
          material={materials.jake_manua_bake}
          position={[0.012, 0, -0.012]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="scarlett_frame_scarlett_manual_bake_0"
          geometry={nodes.scarlett_frame_scarlett_manual_bake_0.geometry}
          material={materials.scarlett_manual_bake}
          position={[3.152, 1.148, 0.751]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Object003_eddie_manuel_bake_0"
          geometry={nodes.Object003_eddie_manuel_bake_0.geometry}
          material={materials.eddie_manuel_bake}
          position={[12.8, 1.645, 3.839]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Object004_holly_manual_bake_0"
          geometry={nodes.Object004_holly_manual_bake_0.geometry}
          material={materials.holly_manual_bake}
          position={[0, 0.006, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Object005_squirrel_manual_bake_0"
          geometry={nodes.Object005_squirrel_manual_bake_0.geometry}
          material={materials.squirrel_manual_bake}
          position={[7.951, 1.306, -0.969]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Object006_tess_manual_bake_0"
          geometry={nodes.Object006_tess_manual_bake_0.geometry}
          material={materials.tess_manual_bake}
          position={[5.384, 1.557, 0.776]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Object007_tiggy_manual_bake_0"
          geometry={nodes.Object007_tiggy_manual_bake_0.geometry}
          material={materials.tiggy_manual_bake}
          position={[1.257, 1.654, -0.959]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="aston_manual_bake_aston_manual_bake_0"
          geometry={nodes.aston_manual_bake_aston_manual_bake_0.geometry}
          material={materials.aston_manual_bake}
          position={[-2.138, 1.557, -0.955]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Object009_propinquity_manual_bake_0"
          geometry={nodes.Object009_propinquity_manual_bake_0.geometry}
          material={materials.propinquity_manual_bake}
          position={[-5.535, 1.645, -0.098]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="pant_pot_plant_pot_0"
          geometry={nodes.pant_pot_plant_pot_0.geometry}
          material={materials.plant_pot}
          position={[1.677, 0.839, -0.235]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Line004_door_manual_bake_0"
          geometry={nodes.Line004_door_manual_bake_0.geometry}
          material={materials.door_manual_bake}
          position={[21.536, 1.295, 0.278]}
          rotation={[Math.PI, -1.527, Math.PI]}
          scale={0.001}
        />
        <mesh
          name="Object046_Material_#49_0"
          geometry={nodes["Object046_Material_#49_0"].geometry}
          material={materials.Material_49}
          position={[12.863, 1.795, -1.218]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="Circle001_xxx_0"
          geometry={nodes.Circle001_xxx_0.geometry}
          material={materials.material}
          position={[12.365, -0.029, 0]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="rainbow001_lens_flare_0"
          geometry={nodes.rainbow001_lens_flare_0.geometry}
          material={materials.lens_flare}
          position={[-8.679, 2.068, 0.004]}
          rotation={[-1.57, 0.009, 0]}
          scale={0.001}
        />
        <mesh
          name="0"
          geometry={nodes["0"].geometry}
          material={materials.Material_585}
          morphTargetDictionary={nodes["0"].morphTargetDictionary}
          morphTargetInfluences={nodes["0"].morphTargetInfluences}
          position={[1.851, -0.006, -0.013]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="1"
          geometry={nodes["1"].geometry}
          material={materials.baked_curtain}
          morphTargetDictionary={nodes["1"].morphTargetDictionary}
          morphTargetInfluences={nodes["1"].morphTargetInfluences}
          position={[11.406, 1.59, 3.651]}
          rotation={[Math.PI, 0.243, -Math.PI]}
          scale={0.001}
        />
        <mesh
          name="2"
          geometry={nodes["2"].geometry}
          material={materials.baked_curtain}
          position={[-7.162, 1.59, 3.451]}
          rotation={[Math.PI, -0.436, Math.PI]}
          scale={0.001}
        />
        <mesh
          name="3"
          geometry={nodes["3"].geometry}
          material={materials.plant}
          morphTargetDictionary={nodes["3"].morphTargetDictionary}
          morphTargetInfluences={nodes["3"].morphTargetInfluences}
          position={[1.677, 0.839, -0.235]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
        <mesh
          name="4"
          geometry={nodes["4"].geometry}
          material={materials.Material_3550}
          morphTargetDictionary={nodes["4"].morphTargetDictionary}
          morphTargetInfluences={nodes["4"].morphTargetInfluences}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/arts-transformed.glb");
