/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 camera.gltf --transform 
Files: camera.gltf [37.2MB] > C:\Users\mohan\Downloads\camera\camera-transformed.glb [740.53KB] (98%)
Author: GrostyBoi (https://sketchfab.com/GrostyBoi)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/zeiss-ikon-53216-ww2-era-camera-e349bebb337a4eb49d75fe89853f9d08
Title: Zeiss Ikon 532/16 | WW2 Era Camera
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/camera-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.defaultMaterial.geometry}
        material={materials.M_ZeissCamera}
        position={[17.531, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/camera-transformed.glb");
