/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 collage.gltf --transform 
Files: collage.gltf [8.6MB] > C:\Users\mohan\Downloads\photo_collage\collage-transformed.glb [123.59KB] (99%)
Author: Christian (https://sketchfab.com/Enzi1984)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/photo-collage-wall-aac0daa4cb7f4d74972f45799e49d42e
Title: photo collage, wall
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/collage-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_5.geometry}
        material={materials["back_panel-black"]}
      />
      <mesh
        geometry={nodes.Object_7.geometry}
        material={materials.Black_Plastic}
      />
      <mesh
        geometry={nodes.Object_9.geometry}
        material={materials.glass}
        position={[0, 0.01, 0]}
      />
      <mesh
        geometry={nodes.Object_11.geometry}
        material={materials.photos}
        position={[0, 0.004, 0]}
      />
    </group>
  );
}

useGLTF.preload("/collage-transformed.glb");
