/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 computer.gltf --transform 
Files: computer.gltf [202MB] > C:\Users\mohan\Downloads\cyberpunk_laptop_concept_design\computer-transformed.glb [1.5MB] (99%)
Author: Berk Gedik (https://sketchfab.com/berkgedik)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cyberpunk-laptop-concept-design-fddc4e68cc6c498b88b19af1a05bd420
Title: CyberPunk Laptop Concept Design
*/

import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/computer-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube004_Auto_01_0.geometry}
        material={materials.Auto_01}
        position={[0, -25.593, 7.313]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Keys_Auto_02_0.geometry}
        material={materials.Auto_02}
        position={[-72.227, -27.683, 35.45]}
        rotation={[-Math.PI / 2, 0, 0.002]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube006_Auto_03_0.geometry}
        material={materials.Auto_03}
        position={[17.369, -25.593, 7.313]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube_Auto_04_0.geometry}
        material={materials.Auto_04}
        position={[0, 50.454, -8.888]}
        rotation={[-1.943, 0, -Math.PI / 2]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube_Screen_0.geometry}
        material={materials.Screen}
        position={[0, 50.454, -8.888]}
        rotation={[-1.943, 0, -Math.PI / 2]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/computer-transformed.glb");
